# Generated by Django 5.1.7 on 2025-04-05 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Актер")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Биография"),
                ),
            ],
            options={
                "verbose_name": "Актер",
                "verbose_name_plural": "Актеры",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Режиссер")),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="Биография"),
                ),
            ],
            options={
                "verbose_name": "Режиссер",
                "verbose_name_plural": "Режиссеры",
            },
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите название фильма",
                        max_length=150,
                        verbose_name="Название",
                    ),
                ),
                (
                    "release_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(2025),
                            django.core.validators.MinValueValidator(1895),
                        ],
                        verbose_name="Год выхода фильма",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите постер",
                        null=True,
                        upload_to="films/posters/",
                        verbose_name="Постер",
                    ),
                ),
                ("publish_date", models.DateField(auto_now_add=True)),
                (
                    "average_rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Рейтинг фильма",
                    ),
                ),
                (
                    "actors",
                    models.ManyToManyField(
                        related_name="films",
                        to="films.actor",
                        verbose_name="В фильме снимались",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="films", to="films.genre", verbose_name="Жанр"
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="films",
                        to="films.producer",
                        verbose_name="Режиссер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
            },
        ),
    ]
