# Generated by Django 5.1.7 on 2025-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0002_alter_film_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Наименование"
            ),
        ),
    ]
