# Generated by Django 5.1.7 on 2025-04-07 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_alter_interaction_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
