# Generated by Django 5.1.7 on 2025-04-10 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0004_alter_interaction_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
