# Generated by Django 5.1.7 on 2025-04-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("films", "0003_alter_genre_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_created=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("knn", "Алгоритм ближайших соседей"),
                            ("pagerank", "Алгоритм PageRank"),
                        ],
                        max_length=9,
                        verbose_name="Алгоритм",
                    ),
                ),
                (
                    "films",
                    models.ManyToManyField(
                        related_name="recommendations",
                        to="films.film",
                        verbose_name="Ваши рекомендации",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Рекомендация",
                "verbose_name_plural": "Рекомендации",
            },
        ),
    ]
